# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# GitHub Pages:
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - developer-tools
plugins:
#   - jekyll-coffeescript
#   - jekyll-default-layout
#   - jekyll-gist
#   - jekyll-github-metadata
#   - jekyll-optional-front-matter
#   - jekyll-paginate
#   - jekyll-readme-index
#   - jekyll-titles-from-headings
#   - jekyll-relative-links
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap


# Site settings
title:            here-and-there
subtitle:         A Bag-of-words with some trivia
description:      This is a personal landing page.
keywords:         Kunal Tyagi kunaltyagi cv blog
language:         "en" # default language of the blog. Language codes: http://www.w3schools.com/tags/ref_language_codes.asp

baseurl:          "/" # the subpath of your site, e.g. /blog
url:              "" # the base hostname & protocol for your site. Have a look at robots.txt as well!
# permalink:        /blog/:categories/:title
permalink:        :year/:month/:day/:title:output_ext
cover:            /assets/fuji.jpg
disqus_shortname: "ktyagi"

# Build settings
sass:
    style: compressed
markdown: kramdown
# kramdown:
#  syntax_highlighter_opts:
#    disable: true
include: ['_pages']

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]
  blanklines: true
  startings: [head, body]

